var GLangTipe = [{
    "notes": "简体中文",
    "lang": "zh-cn",
    "lang1": "您已兑换过，请勿重复兑换",
    "lang2": "抱歉，您尚未获得测试资格，请关注社群放号信息",
    "lang3": "已兑换",
    "lang4": "登录成功",
    "lang5": "领取成功！请留意游戏内邮件",
    "lang6": "领取失败，请重试。",
    "lang8": "立即登录兑换奖励",
    "lang9": "登出",
    "lang10": "兑换",
    "lang11": "登录"
}, {
    "notes": "English",
    "lang": "en",
    "lang1": "You've already redeemed.",
    "lang2": "Sorry, you have not gained access to the test yet. Stay tuned to our community updates for upcoming giveaways.",
    "lang3": "Redeemed",
    "lang4": "Login Successful",
    "lang5": "Successfully claimed! Please check your in-game mail.",
    "lang6": "Failed to claim. Please try again later.",
    "lang8": "Log in & Redeem Now",
    "lang9": "Log out",
    "lang10": "Redeem",
    "lang11": "Log In"
}, {
    "notes": "French",
    "lang": "fr",
    "lang1": "Vous avez déjà échangé.",
    "lang2": "Désolé, vous n’avez pas encore accès au test. Restez à l’écoute des mises à jour de notre communauté pour les prochains cadeaux.",
    "lang3": "Échangé",
    "lang4": "Connexion réussie",
    "lang5": "Récupération réussie ! Veuillez consulter votre messagerie.",
    "lang6": "La récupération a échoué. Veuillez réessayer plus tard.",
    "lang8": "Se connecter et échanger maintenant",
    "lang9": "Déconnexion",
    "lang10": "Échanger",
    "lang11": "Se connecter"
}, {
    "notes": "Spanish",
    "lang": "es",
    "lang1": "Ya realizaste el canje.",
    "lang2": "Lo sentimos, aún no tienes acceso a la prueba. Mantente al tanto de las noticias de nuestra comunidad sobre los próximos regalos.",
    "lang3": "Canjeado",
    "lang4": "Inicio de sesión exitoso",
    "lang5": "¡Obtenido! Revisa tu correo del juego.",
    "lang6": "Error al obtener. Reinténtalo más tarde.",
    "lang8": "Iniciar sesión y canjear ahora",
    "lang9": "Cerrar sesión",
    "lang10": "Canjear",
    "lang11": "Iniciar sesión"
}, {
    "notes": "Russian",
    "lang": "ru",
    "lang1": "Вы уже использовали.",
    "lang2": "К сожалению, вы еще не получили доступ к тестированию. Следите за обновлениями сообщества, чтобы не пропустить будущие розыгрыши.",
    "lang3": "Использовано",
    "lang4": "Вход выполнен успешно",
    "lang5": "Успешно получено! Проверьте свою внутриигровую почту.",
    "lang6": "Не удалось получить. Повторите попытку позже.",
    "lang8": "Войти и применить",
    "lang9": "Выйти",
    "lang10": "Применить",
    "lang11": "Войти"
}, {
    "notes": "German",
    "lang": "de",
    "lang1": "Das hast du bereits eingelöst.",
    "lang2": "Leider hast du noch keinen Testzugang erhalten. Bleib dran, unsere Community-Updates informieren dich über kommende Giveaways.",
    "lang3": "Eingelöst",
    "lang4": "Erfolgreich angemeldet",
    "lang5": "Erfolgreich abgeholt! Bitte überprüfe deine Post im Spiel.",
    "lang6": "Abholen fehlgeschlagen. Bitte versuche es später erneut.",
    "lang8": "Jetzt anmelden & einlösen",
    "lang9": "Abmelden",
    "lang10": "Einlösen",
    "lang11": "Anmelden"
}, {
    "notes": "Arabic（以线下文件为准）",
    "lang": "ar",
    "lang1": "لقد قمت بالاسترداد بالفعل.",
    "lang2": "معذرة، ليست لديك إمكانية الوصول إلى الإصدار التجريبي بعد. ترقب المستجدات من مجتمعنا بشأن الهدايا القادمة.",
    "lang3": "تم الاسترداد",
    "lang4": "تم تسجيل الدخول بنجاح",
    "lang5": "تم الحصول بنجاح! يُرجى التحقق من بريدك في اللعبة.",
    "lang6": "تعذّر الحصول. يُرجى المحاولة مرة أخرى لاحقًا.",
    "lang8": "قم بتسجيل الدخول والاسترداد الآن",
    "lang9": "تسجيل الخروج",
    "lang10": "استرداد",
    "lang11": "تسجيل الدخول"
}, {
    "notes": "繁体中文",
    "lang": "zh-tw",
    "lang1": "您已兌換過，請勿重複兑換",
    "lang2": "抱歉，您尚未獲得測試資格，請關注社群放號資訊",
    "lang3": "已兑換",
    "lang4": "登入成功",
    "lang5": "領取成功！請留意遊戲內郵件",
    "lang6": "領取失敗，請重試。",
    "lang8": "立即登錄兑換獎勵",
    "lang9": "登出",
    "lang10": "前往兌換",
    "lang11": "登入"
}, {
    "notes": "Thai",
    "lang": "th",
    "lang1": "คุณเคยแลกรับสิทธิ์ไปแล้ว ห้ามแลกซ้ำ",
    "lang2": "ขออภัย คุณไม่ได้รับสิทธิ์ทดสอบ กรุณาติดตามข่าวปล่อยสิทธิ์ทดสอบเพิ่มเติมจากชุมชน",
    "lang3": "แลกรับสิทธิ์แล้ว",
    "lang4": "เข้าสู่ระบบสำเร็จ",
    "lang5": "รับสำเร็จ! กรุณาตรวจสอบกล่องจดหมายในเกม",
    "lang6": "รับล้มเหลว กรุณาลองใหม่",
    "lang8": "ล็อกอินแลกรางวัลทันที",
    "lang9": "ลงชื่อออก",
    "lang10": "ไปแลก",
    "lang11": "เข้าสู่ระบบ"
}, {
    "notes": "Vietnamese",
    "lang": "vi",
    "lang1": "Bạn đã đổi rồi.",
    "lang2": "Rất tiếc, bạn chưa nhận được quyền chơi thử. Hãy để ý theo dõi thông tin cập nhật trong cộng đồng của chúng tôi để biết các phần quà sắp tới nhé.",
    "lang3": "Đã đổi",
    "lang4": "Đăng nhập thành công",
    "lang5": "Đã nhận thành công! Vui lòng kiểm tra hộp thư trong game của bạn.",
    "lang6": "Chưa nhận được. Vui lòng thử lại sau.",
    "lang8": "Đăng nhập và Đổi thưởng ngay",
    "lang9": "Đăng xuất",
    "lang10": "Đổi",
    "lang11": "Đăng Nhập"
}, {
    "notes": "Indonesian",
    "lang": "id",
    "lang1": "Kamu sudah melakukan penukaran.",
    "lang2": "Maaf, kamu belum mendapatkan akses ke uji coba. Terus ikuti pembaruan komunitas kami untuk giveaway mendatang.",
    "lang3": "Sudah ditukarkan",
    "lang4": "Berhasil Login",
    "lang5": "Berhasil diklaim! Periksa pesan dalam game kamu.",
    "lang6": "Gagal mengeklaim. Coba lagi nanti.",
    "lang8": "Log in & Tukar Sekarang",
    "lang9": "Log out",
    "lang10": "Tukar",
    "lang11": "Log In"
}, {
    "notes": "Portuguese",
    "lang": "pt",
    "lang1": "Você já resgatou.",
    "lang2": "Desculpe, você ainda não obteve acesso ao teste. Não perca as atualizações da nossa comunidade para saber dos próximos brindes.",
    "lang3": "Resgatado",
    "lang4": "Login bem-sucedido",
    "lang5": "Resgate bem-sucedido! Verifique as suas mensagens dentro do jogo.",
    "lang6": "Falha ao resgatar. Tente novamente mais tarde.",
    "lang8": "Entre e Resgate Agora",
    "lang9": "Sair",
    "lang10": "Resgatar",
    "lang11": "Entrar"
}, {
    "notes": "Korean",
    "lang": "ko",
    "lang1": "이미 교환하셨습니다. 중복 교환은 불가능합니다.",
    "lang2": "귀하는 아직 테스트 참여 자격이 없습니다. SNS의 테스트 참여 자격 배포 안내를 확인해 주세요.",
    "lang3": "교환 완료",
    "lang4": "로그인 성공",
    "lang5": "수령에 성공했습니다! 게임 내 우편을 확인하세요.",
    "lang6": "수령에 실패했습니다. 다시 시도하세요.",
    "lang8": "지금 로그인하고 보상 교환",
    "lang9": "로그아웃",
    "lang10": "교환하기",
    "lang11": "로그인"
}, {
    "notes": "Japanese",
    "lang": "ja",
    "lang1": "交換済みです。重複して交換できません",
    "lang2": "申し訳ございません、あなたはまだテスト資格を獲得していません。コミュニティの最新情報をご確認ください",
    "lang3": "交換済み",
    "lang4": "ログインしました",
    "lang5": "受取成功！ゲーム内メールをご確認ください",
    "lang6": "受取失敗。もう一度お試しください。",
    "lang8": "今すぐログインして報酬を交換しましょう",
    "lang9": "ログアウト",
    "lang10": "引き換える",
    "lang11": "ログイン"
}, {
    "notes": "Turkish",
    "lang": "tr",
    "lang1": "Önceden kullanmışsın.",
    "lang2": "Üzgünüz, henüz test için erişimin yok. Gelecek erişim hakları için topluluk güncellemelerini takip et.",
    "lang3": "Kullanıldı",
    "lang4": "Giriş Başarılı",
    "lang5": "Başarıyla alındı! Lütfen oyundaki posta kutunu kontrol et.",
    "lang6": "Alınamadı. Lütfen daha sonra tekrar dene",
    "lang8": "Oturum Aç ve Hemen Kullan",
    "lang9": "Oturumu Kapat",
    "lang10": "Kullan",
    "lang11": "Oturum Aç"
}, {
    "notes": "Malay",
    "lang": "ms",
    "lang1": "Anda sudah menuntut.",
    "lang2": "Harap maaf, anda masih belum memperoleh akses kepada ujian. Ikuti kemas kini komuniti kami untuk pemberian yang akan datang.",
    "lang3": "Dituntut",
    "lang4": "Log Masuk Berjaya",
    "lang5": "Berjaya dituntut! Sila semak mel dalam permainan anda.",
    "lang6": "Gagal dituntut. Sila cuba lagi nanti.",
    "lang8": "Log masuk dan Tebus Sekarang",
    "lang9": "Log keluar",
    "lang10": "Tebus",
    "lang11": "Log Masuk"
}];