var GLanguage = {
    default: {},
    en: {
        "title": "Redemption Center",
        "description": "Delta Force is a definitive free-to-play first-person tactical shooter. Experience the ultimate test of skill and strategy! Available on PC, console, and mobile soon!",
        "keywords": "Delta Force Delta Force、Delta Force Preregistration、Delta Force Preorder、Delta Force Release、Delta Force New、Delta Force New Game、New Delta Force Game、Delta Force 2023、DF 2023、Delta Force relaunch、Delta Force Reactivate、Arena Breakout、Arena Breakout: Infinite、EFT、Escape from Tarkov、Realistic FPS、Extraction Shooter",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "English",
        "lang": "en",
        "lang1": "Sorry, your account has reached the redemption limit for this gift pack.",
        "lang2": "Sorry, you have not gained access to the test yet. Stay tuned to our community updates for upcoming giveaways.",
        "lang3": "Redeemed",
        "lang4": "Login Successful",
        "lang5": "Successfully claimed! Please check your in-game mail.",
        "lang6": "Failed to claim. Please try again later.",
        "lang8": "Log in & Redeem Now",
        "lang9": "Log out",
        "lang10": "Redeem",
        "lang11": "Log In",
        "lang12": "The CDKey entered is not valid. Please try again.",
        "lang178": "Terms of Use",
        "lang179": "Privacy Policy",
        "lang180": "Cookie Policy",
        "lang181": "License Information",
        "networkError": "Network error. Please try again later.",
        "lang_1": "You've already redeemed this code.",
        "event_reward": "Event Reward",
        "copyright": "Congratulations! You've received an event reward. Please find it attached. Thank you for participating, and enjoying the game!",
        "creator_reward": "Creator Rewards",
        "creator_thanks_hint": "Thank you for joining the Creator Event. Here is your event reward. Wishing you endless fun in Garena Delta Force: Hawk Ops!",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        "footLink3": "https://deltaforce.garena.com/en/",
        "error_hint_400067": "The current user has reached the redemption limit for the CD key group.",
        "error_hint_400068": "CD key redemption limit reached.",
        "error_hint_400069": "CD key redemption not yet available.",
        "error_hint_400070": "This CD key redemption period ended.",
        "error_hint_400072": "The user has already redeemed the CD key.",
        "error_hint_400073": "CD key pack configuration error."
    },
    de: {
        title: "Einlösezentrum",
        description: "Delta Force ist ein ultimativer, kostenloser und taktischer First-Person-Shooter. Verfügbar für PC, Konsolen und Handy.",
        keywords: "Delta Force Delta Force, Delta Force Mobile, Delta Force Online, DF Mobile, Delta Force Home Page, FPS, esports, teambasiertes gameplay, strategisches gameplay, SOL, gaming-tipps von pros, taktisches gameplay, klassenbasiert, taktischer shooter",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "German",
        lang: "de",
        lang1: "Leider kannst du auf deinem Konto keinen weiteren CD-Key für dieses Geschenk einlösen.",
        lang2: "Leider hast du noch keinen Testzugang erhalten. Bleib dran, unsere Community-Updates informieren dich über kommende Giveaways.",
        lang3: "Eingelöst",
        lang4: "Erfolgreich angemeldet",
        lang5: "Erfolgreich abgeholt! Bitte überprüfe deine Post im Spiel.",
        lang6: "Abholen fehlgeschlagen. Bitte versuche es später erneut.",
        lang8: "Jetzt anmelden & einlösen",
        lang9: "Abmelden",
        lang10: "Einlösen",
        lang11: "Anmelden",
        lang12: "Der eingegebene CD-Key ist nicht gültig. Bitte versuche es erneut.",
        lang178: "Nutzungsbedingungen",
        lang179: "Datenschutzrichtlinie",
        lang180: "Cookie-Richtlinie",
        lang181: "License Information",
        networkError: "Netzwerkfehler. Bitte später erneut versuchen.",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        footLink3: "https://deltaforce.garena.com/en/"
    },
    fr: {
        title: "Delta Force Centre d'échanges",
        description: "Delta Force est le FPS tactique gratuit ultime. Disponible sur PC, consoles et mobile.",
        keywords: "Delta Force, Delta Force Mobile, Delta Force Online, DF Mobile, page d'accueil Delta Force, FPS, esports, gameplay en équipe, gameplay stratégique, SOL, astuces de joueurs pro, gameplay tactique, différentes classes, jeu de tir tactique",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "French",
        lang: "fr",
        lang1: "Malheureusement, votre compte n'est pas disponible pour échanger plus de CDKey de ce pack cadeau.",
        lang2: "Désolé, vous n’avez pas encore accès au test. Restez à l’écoute des mises à jour de notre communauté pour les prochains cadeaux.",
        lang3: "Échangé",
        lang4: "Connexion réussie",
        lang5: "Récupération réussie ! Veuillez consulter votre messagerie.",
        lang6: "La récupération a échoué. Veuillez réessayer plus tard.",
        lang8: "Se connecter et échanger maintenant",
        lang9: "Déconnexion",
        lang10: "Échanger",
        lang11: "Se connecter",
        lang12: "La clé d'activation entrée n’est pas valide. Veuillez réessayer.",
        lang178: "Conditions d'utilisation",
        lang179: "Politique de confidentialité",
        lang180: "Politique en matière de cookies",
        lang181: "License Information",
        notes: "French",
        networkError: "Erreur réseau. Veuillez réessayer ultérieurement.",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        footLink3: "https://deltaforce.garena.com/en/"
    },
    ar: {
        "title": "مركز الاسترداد",
        "description": "لعبة Delta Force هي لعبة تصويب تكتيكية مجانية فائقة الروعة من منظور الشخص الأول. تتوفر اللعبة على أجهزة الكمبيوتر والأجهزة المخصصة للألعاب والهواتف المحمولة.",
        "keywords": "Delta Force, Delta، Force Mobile، Delta Force Online، DF Mobile، الصفحة الرئيسية للعبة Delta Force،FPS,، رياضات إلكترونية، أسلوب لعب جماعي، أسلوب لعب إستراتيجيات، SOL، نصائح لعب احترافية، أسلوب لعب تكتيكي، على أساس الفئة، تصويب تكتيكي",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Arabic（以线下文件为准）",
        "lang": "ar",
        "lang1": "عذرًا، حسابك غير جاهز لاسترداد أي مفاتيح CDKey أخرى لحزمة الهدايا هذه.",
        "lang2": "معذرة، ليست لديك إمكانية الوصول إلى الإصدار التجريبي بعد. ترقب المستجدات من مجتمعنا بشأن الهدايا القادمة.",
        "lang3": "تم الاسترداد",
        "lang4": "تم تسجيل الدخول بنجاح",
        "lang5": "تم الحصول بنجاح! يُرجى التحقق من بريدك في اللعبة.",
        "lang6": "تعذّر الحصول. يُرجى المحاولة مرة أخرى لاحقًا.",
        "lang8": "قم بتسجيل الدخول والاسترداد الآن",
        "lang9": "تسجيل الخروج",
        "lang10": "استرداد",
        "lang11": "تسجيل الدخول",
        "lang12": "مفتاح CDKey الذي أدخلته غير صالح. يُرجى المحاولة مرة أخرى.",
        "lang178": "شروط الاستخدام",
        "lang179": "سياسة الخصوصية",
        "lang180": "سياسة ملفات الارتباط",
        "lang181": "License Information",
        "networkError": "خطأ في اتصال الشبكة. يُرجى إعادة المحاولة في وقتٍ لاحق.",
        "lang_1": "لقد قمت بالاسترداد بالفعل.",
        "event_reward": "مكافأة الفعالية",
        "copyright": "تهانينا! لقد ربحت إحدى المكافآت الخاصة بالفعالية، وأرفقناها بهذه الرسالة. نشكرك على الانضمام إلى الفعالية، ونتمنى لك الاستمتاع باللعبة!",
        "creator_reward": "مكافآت صانع المحتوى",
        "creator_thanks_hint": "نشكرك على الانضمام إلى فعالية صانع المحتوى. إليك مكافأتك للفعالية. نتمنى لك متعة هائلة بلعب Garena Delta Force® - Official !",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        "footLink3": "https://deltaforce.garena.com/ar/",
        "error_hint_400067": "تم الوصول إلى الحد الأقصى لاسترداد مفتاح CD.",
        "error_hint_400068": "لقد وصل المستخدم الحالي إلى الحد الأقصى لاسترداد مجموعة مفاتيح CD.",
        "error_hint_400069": "استرداد رمز CD غير متاح حاليًا.",
        "error_hint_400070": "انتهت فترة استرداد رمز CD.",
        "error_hint_400072": "استرد المستخدم بالفعل رمز CD.",
        "error_hint_400073": "خطأ في تكوين حزمة رمز CD."
    },
    es: {
        "title": "Centro de canjes",
        "description": "Delta Force es el juego definitivo de disparos táctico en primera persona totalmente gratuito. Disponible para PC, consolas y dispositivos móviles.",
        "keywords": "Delta Force Delta Force, Delta Force Mobile, Delta Force Online, DF Mobile, Delta Force Home, FPS, esports, juego por equipos, estrategias de juego, SOL, consejos pro, gaming, juego táctico, class-based, shooter táctico",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Spanish",
        "lang": "es",
        "lang1": "Lo sentimos, tu cuenta alcanzó el número máximo de canjes para este código",
        "lang2": "Lo sentimos, aún no tienes acceso a la prueba. Mantente al tanto de las noticias de nuestra comunidad sobre los próximos regalos.",
        "lang3": "Canjeado",
        "lang4": "Inicio de sesión exitoso",
        "lang5": "¡Obtenido! Revisa tu correo del juego.",
        "lang6": "Error al obtener. Reinténtalo más tarde.",
        "lang8": "Inicia sesión y canjea ahora",
        "lang9": "Cerrar sesión",
        "lang10": "Canjear",
        "lang11": "Iniciar sesión",
        "lang12": "El código no es válido. Vuelve a intentarlo.",
        "lang178": "Condiciones de uso",
        "lang179": "Política de privacidad",
        "lang180": "Política de cookies",
        "lang181": "License Information",
        "networkError": "Error de red. Vuelve a intentarlo más tarde.",
        "lang_1": "Ya canjeaste este código",
        "event_reward": "Recompensas de Evento",
        "copyright": "¡Felicidades! Recibiste una recompensa de evento, podrás encontrarla aquí. Gracias por unirte al evento, ¡que disfrutes del juego!",
        "creator_reward": "Recompensas para creadores",
        "creator_thanks_hint": "Gracias por unirte al evento de Creadores. Aquí tienes tu recompensa del evento. ¡Esperamos que te diviertas mucho en Delta Force!",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_es.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_es.html",
        "footLink3": "https://deltaforce.garena.com/es/",
        "error_hint_400067": "Se alcanzó el límite de canjes de la clave CD.",
        "error_hint_400068": "El usuario actual alcanzó el límite de canjes del grupo de clave CD.",
        "error_hint_400069": "Aún no está disponible el canje de clave CD.",
        "error_hint_400070": "El periodo de canje de esta clave CD finalizó.",
        "error_hint_400072": "El usuario ya usó la clave CD.",
        "error_hint_400073": "Error de paquete de configuración de clave CD."
    },
    ru: {
        title: "Центр обмена",
        description: "Delta Force — это бесплатный тактический шутер от первого лица. Доступен на ПК, консолях и мобильных устройствах.",
        keywords: "Delta Force, Delta Force Mobile, Delta Force Online, DF Mobile, главная страница Delta Force, FPS, киберспорт, командная игра, стратегическая игра, SOL, профессиональные игровые советы, тактическая игра, на основе классов, тактический шутер",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "Russian",
        lang: "ru",
        lang1: "Извините, лимит использований этого ключа CDKey для вашего аккаунта исчерпан.",
        lang2: "К сожалению, вы еще не получили доступ к тестированию. Следите за обновлениями сообщества, чтобы не пропустить будущие розыгрыши.",
        lang3: "Использовано",
        lang4: "Вход выполнен успешно",
        lang5: "Успешно получено! Проверьте свою внутриигровую почту.",
        lang6: "Не удалось получить. Повторите попытку позже.",
        lang8: "Войти и применить",
        lang9: "Выйти",
        lang10: "Применить",
        lang11: "Войти",
        lang12: "Введенный ключ CDKey недействителен. Повторите попытку.",
        lang178: "Условия использования",
        lang179: "Политика конфиденциальности",
        lang180: "Политика использования файлов cookie",
        lang181: "License Information",
        networkError: "Ошибка сети. Повторите попытку позже.",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        "footLink3": "https://deltaforce.garena.com/en/"
    },
    "zh-tw": {
        "title": "兌換中心",
        "description": "《三角洲行動》是一款免費暢玩的終極體驗第一人稱的戰術射擊，將在PC、主機、手遊多平台上線。",
        "keywords": "三角洲，三角洲特種部隊，三角洲行動，黑鷹墜落，三角洲手遊，三角洲新遊，三角洲電競，FPS，三角洲官網，電競，合作電競，SOL，多平台",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "繁体中文",
        "lang": "zh-tw",
        "lang1": "您的帳號已達CD Key兌換上限",
        "lang2": "抱歉，您尚未獲得測試資格，請關注社群放號資訊",
        "lang3": "已兌換",
        "lang4": "登入成功",
        "lang5": "領取成功！請留意遊戲內郵件",
        "lang6": "領取失敗，請重試。",
        "lang8": "立即登入兌換獎勵",
        "lang9": "登出",
        "lang10": "前往兌換",
        "lang11": "登入",
        "lang12": "輸入的CDKey有誤，請重新輸入。",
        "lang178": "服務條款",
        "lang179": "隱私權政策",
        "lang180": "Cookie政策",
        "lang181": "License Information",
        "networkError": "網路錯誤，請稍後再試",
        "lang_1": "您已兌換過，請勿重複兌換",
        "event_reward": "活動獎勵",
        "copyright": "恭喜您獲得了活動獎勵，請收下附件中您的獎品。感謝您參與我們的活動，祝您遊玩愉快！",
        "creator_reward": "創作者獎勵",
        "creator_thanks_hint": "感謝您參加創作者活動，這是您的活動獎勵，請您查收。祝您遊戲愉快！",
        "footLink1": "https://terms.support.garena.com/tw",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_zh-TW.html",
        "footLink3": "https://deltaforce.garena.com/zh_tw/",
        "error_hint_400067": "當前用戶達到cdkey組兌換上限",
        "error_hint_400068": "cdkey達到兌換上限",
        "error_hint_400069": "未到cdkey兌換時間",
        "error_hint_400070": "cdkey兌換時間結束",
        "error_hint_400072": "該用戶已兌換過cdkey",
        "error_hint_400073": "cdkey禮包組配置錯誤"
    },
    th: {
        "title": "ศูนย์แลกรางวัล",
        "description": "Delta Force คือสุดยอดเกม FPS เชิงกลยุทธ์ที่เล่นฟรี ซึ่งกำลังจะเปิดให้บริการบนหลายแพลตฟอร์ม ทั้ง PC คอนโซล และเกมมือถือ",
        "keywords": "เดลต้าฟอร์ซ, กองกำลังพิเศษเดลต้าฟอร์ซ, Delta Force แบล็คฮอว์คดาวน์, เดลต้าฟอร์ซโมบาย, เกมเดลต้าฟอร์ซ, อีสปอร์ตเดลต้าฟอร์ซ, FPS, โฮมเพจเดลต้าฟอร์ซ, อีสปอร์ต, อีสปอร์ตแบบทีม, SOL, ข้ามแพลตฟอร์ม",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Thai",
        "lang": "th",
        "lang1": "ขออภัย บัญชีของคุณได้ใช้สิทธิ์แลก CD Key ประเภทนี้ครบแล้ว",
        "lang2": "ขออภัย คุณไม่ได้รับสิทธิ์ทดสอบ กรุณาติดตามข่าวปล่อยสิทธิ์ทดสอบเพิ่มเติมจากชุมชน",
        "lang3": "แลกรับสิทธิ์แล้ว",
        "lang4": "เข้าสู่ระบบสำเร็จ",
        "lang5": "รับสำเร็จ! กรุณาตรวจสอบกล่องจดหมายในเกม",
        "lang6": "ล้มเหลว กรุณาลองใหม่",
        "lang8": "ล็อกอินแลกรางวัลทันที",
        "lang9": "ลงชื่อออก",
        "lang10": "ไปแลก",
        "lang11": "เข้าสู่ระบบ",
        "lang12": "CD Key ไม่ถูกต้อง กรุณากรอกใหม่",
        "lang178": "เงื่อนไขการให้บริการ",
        "lang179": "ข้อตกลงความเป็นส่วนตัว",
        "lang180": "นโยบายคุกกี้",
        "lang181": "License Information",
        "networkError": "เครือข่ายขัดข้อง กรุณาลองอีกครั้งในภายหลัง",
        "lang_1": "คุณเคยแลกรับสิทธิ์ไปแล้ว ห้ามแลกซ้ำ",
        "event_reward": "รางวัลกิจกรรม",
        "copyright": "ยินดีด้วย คุณได้รับรางวัลกิจกรรม กรุณากดรับของขวัญที่แนบมา ขอขอบคุณที่ร่วมสนุกกิจกรรมของพวกเรา ขอให้เล่นเกมอย่างมีความสุข!",
        "creator_reward": "รางวัลครีเอเตอร์",
        "creator_thanks_hint": "ขอขอบคุณที่ร่วมสนุกกิจกรรมครีเอเตอร์ นี่คือรางวัลของคุณ กรุณาตรวจรับ ขอให้สนุกกับการเล่นเกม!",
        "footLink1": "https:www.garena.co.th/tos",
        "footLink2": "https://www.garena.co.th/privacy",
        "footLink3": "https://deltaforce.garena.com/th/",
        "error_hint_400067": "ขณะนี้ผู้ใช้ได้ใช้สิทธิ์แลก CDKey ครบแล้ว",
        "error_hint_400068": "CDKey ถูกแลกครบแล้ว",
        "error_hint_400069": "ยังไม่ถึงเวลาแลก CDKey",
        "error_hint_400070": "หมดเวลาแลก CDKey แล้ว",
        "error_hint_400072": "ผู้ใช้นี้แลก CDKey แล้ว",
        "error_hint_400073": "แพ็กของขวัญ CDKey ผิดพลาด"
    },
    id: {
        "title": "Reedem Code Center",
        "description": "Delta Force adalah game first-person shooter taktis ultima yang gratis dimainkan. Tersedia di PC, konsol, dan perangkat seluler.",
        "keywords": "Delta Force, Pasukan Khusus Delta Force, Delta Force, Black Hawk Down, Delta Force Mobile, Delta Force Baru, Delta Force Esports, FPS, Situs Web Resmi Delta Force, Esports, Esports Tim, SOL, Multiplatform",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Indonesian",
        "lang": "id",
        "lang1": "Maaf, akunmu tidak bisa melakukan penukaran kode ini lagi.",
        "lang2": "Maaf, kamu belum mendapatkan akses ke uji coba. Terus ikuti pembaruan komunitas kami untuk giveaway mendatang.",
        "lang3": "Sudah ditukarkan",
        "lang4": "Berhasil Login",
        "lang5": "Berhasil diklaim! Periksa pesan dalam game kamu.",
        "lang6": "Gagal mengeklaim. Coba lagi nanti.",
        "lang8": "Login & Redeem Sekarang",
        "lang9": "Logout",
        "lang10": "Redeem",
        "lang11": "LogIn",
        "lang12": "Kode yang dimasukkan tidak valid. Harap coba lagi.",
        "lang178": "Terms of Use",
        "lang179": "Privacy Policy",
        "lang180": "Cookie Policy",
        "lang181": "License Information",
        "networkError": "Kesalahan jaringan. Coba lagi nanti.",
        "lang_1": "Kamu sudah melakukan penukaran.",
        "event_reward": "Hadiah Event",
        "copyright": "Selamat! Kamu sudah menerima hadiah event. Silakan diklaim!",
        "creator_reward": "Hadiah Kreator",
        "creator_thanks_hint": "Terima kasih telah bergabung di Event Kreator. Silahkan klaim hadiahmu! Semoga kamu bersenang-senang di Delta Force: Hawk Ops!",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_id.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_id.html",
        footLink3: "https://deltaforce.garena.com/id/",
        "error_hint_400067": "Batas penukaran CD Key telah tercapai.",
        "error_hint_400068": "Pengguna saat ini telah mencapai batas penukaran untuk grup CD Key.",
        "error_hint_400069": "Penukaran CD Key belum tersedia.",
        "error_hint_400070": "Periode penukaran CD Key ini telah berakhir.",
        "error_hint_400072": "Pengguna ini sudah menukarkan CD Key.",
        "error_hint_400073": "Kesalahan konfigurasi paket CD Key."
    },
    vi: {
        "title": "Trung Tâm Đổi Quà",
        "description": "Delta Force là tựa game bắn súng chiến thuật góc nhìn thứ nhất tuyệt đỉnh và miễn phí. Tựa game này đang có các phiên bản trên PC, máy chơi game, và điện thoại di động.",
        "keywords": "Lực lượng Delta, lính đặc chủng Delta, Delta Force, Diều hâu gãy cánh, game mobile Delta, e-sports Delta, FPS, trang web chính thức Delta, e-sports, e-sports hợp tác, SOL, đa nền tảng",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Vietnamese",
        "lang": "vi",
        "lang1": "Xin lỗi, tài khoản của bạn không thể đổi thêm CDKey của gói quà này.",
        "lang2": "Rất tiếc, bạn chưa nhận được quyền chơi thử. Hãy để ý theo dõi thông tin cập nhật trong cộng đồng của chúng tôi để biết các phần quà sắp tới nhé.",
        "lang3": "Đã đổi",
        "lang4": "Đăng nhập thành công",
        "lang5": "Đã nhận thành công! Vui lòng kiểm tra hộp thư trong game của bạn.",
        "lang6": "Chưa nhận được. Vui lòng thử lại sau.",
        "lang8": "Đăng nhập và Đổi thưởng ngay",
        "lang9": "Đăng xuất",
        "lang10": "Đổi",
        "lang11": "Đăng Nhập",
        "lang12": "CDKey đã nhập không hợp lệ. Vui lòng thử lại.",
        "lang178": "Điều khoản dịch vụ",
        "lang179": "Thỏa thuận bảo mật",
        "lang180": "Thỏa thuận Cookie",
        "lang181": "License Information",
        "networkError": "Lỗi mạng, vui lòng thử lại sau",
        "lang_1": "Bạn đã đổi rồi.",
        "event_reward": "Phần Thưởng Sự Kiện",
        "copyright": "Xin chúc mừng! Bạn đã nhận được phần thưởng sự kiện. Hãy xem trong phần đính kèm. Cảm ơn bạn đã tham gia sự kiện, và hãy cùng tận hưởng trò chơi nhé!",
        "creator_reward": "Phần Thưởng Dành Cho Nhà Sáng Tạo",
        "creator_thanks_hint": "Cảm ơn bạn đã tham gia Sự Kiện Dành Cho Nhà Sáng Tạo. Đây là phần thưởng sự kiện của bạn. Chúc bạn chơi Garena Delta Force vui vẻ!",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        "footLink3": "https://deltaforce.garena.com/en/"
    },
    pt: {
        "title": "Central de Resgate",
        "description": "Delta Force é o jogo de tiro em primeira pessoa tático free-to-play definitivo. Disponível para PC, consoles e dispositivos móveis.",
        "keywords": "Delta Force, Delta Force, Delta Force Mobile, Delta Force Online, DF Mobile, Página inicial do Delta Force, FPS, esports, jogo em equipe, jogo de estratégias, SOL, dicas de jogo profissionais, jogo tático, baseado em classes, tiro tático",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Portuguese",
        "lang": "pt",
        "lang1": "Desculpe, a sua conta não está disponível para mais resgates de PINs deste tipo.",
        "lang2": "Desculpe, você ainda não obteve acesso ao teste. Não perca as atualizações da nossa comunidade para saber dos próximos brindes.",
        "lang3": "Resgatado",
        "lang4": "Login bem-sucedido",
        "lang5": "Resgate bem-sucedido! Verifique as suas mensagens dentro do jogo.",
        "lang6": "Falha ao resgatar. Tente novamente mais tarde.",
        "lang8": "Entre e Resgate Agora",
        "lang9": "Sair",
        "lang10": "Resgatar",
        "lang11": "Entrar",
        "lang12": "O PIN inserido é inválido. Tente novamente.",
        "lang178": "Termos de Uso",
        "lang179": "Política de privacidade",
        "lang180": "Política de Cookies",
        "lang181": "License Information",
        "networkError": "Erro de conexão. Tente novamente mais tarde.",
        "lang_1": "Você já resgatou.",
        "event_reward": "Recompensa do Evento",
        "copyright": "Parabéns! Você recebeu uma recompensa do evento. A sua recompensa está em anexo. Obrigado por participar do evento e divirta-se!",
        "creator_reward": "Recompensas para Criadores",
        "creator_thanks_hint": "Obrigado por participar do Evento para Criadores. Aqui está a sua recompensa. Esperamos que divirta-se jogando o Garena Delta Force!",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_pt.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_pt.html",
        "footLink3": "https://deltaforce.garena.com/pt/",
        "error_hint_400067": "Limite de resgates da chave de CD atingido.",
        "error_hint_400068": "O usuário atual atingiu o limite de resgates do grupo de chaves de CD.",
        "error_hint_400069": "O resgate da chave de CD ainda não está disponível.",
        "error_hint_400070": "O período de resgate desta chave de CD foi encerrado.",
        "error_hint_400072": "O usuário já resgatou a chave de CD.",
        "error_hint_400073": "Erro na configuração do pacote da chave de CD."
    },
    ko: {
        title: "Delta Force 교환센터",
        description: "<델타 포스: 호크 옵스>는 궁극적인 체험을 선사하는 무료 FPS 게임으로, PC, 콘솔, 모바일 등 다양한 플랫폼에 출시될 예정입니다.",
        keywords: "델타 포스, 델타 포스 특수부대, Delta Force, 블랙이글스 추락, 델타 포스 모바일, 델타 포스 신규 게임, 델타 포스 e스포츠, FPS, 델타 포스 홈페이지, e스포츠, 팀전, SOL, 멀티 플랫폼",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "Korean",
        lang: "ko",
        lang1: "계정의 해당 cdkey가 교환 상한에 도달하였습니다.",
        lang2: "귀하는 아직 테스트 참여 자격이 없습니다. SNS의 테스트 참여 자격 배포 안내를 확인해 주세요.",
        lang3: "교환 완료",
        lang4: "로그인 성공",
        lang5: "수령에 성공했습니다! 게임 내 우편을 확인하세요.",
        lang6: "수령에 실패했습니다. 다시 시도하세요.",
        lang8: "지금 로그인하고 보상 교환",
        lang9: "로그아웃",
        lang10: "교환하기",
        lang11: "로그인",
        lang12: "잘못된 CDK를 입력하셨습니다. 다시 입력하세요.",
        lang178: "서비스 이용 약관",
        lang179: "개인정보 보호 정책",
        lang180: "쿠키 이용 약관",
        lang181: "License Information",
        networkError: "네트워크 오류, 잠시 뒤에 재시도하세요",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        footLink3: "https://deltaforce.garena.com/en/"
    },
    ja: {
        title: "Delta Force 交換センター",
        description: "『デルタフォース ホークオプス』は基本プレイ無料の「究極の体験」を味わえる一人称タクティカルシューティングゲーム。マルチプラットフォーム（PC、家庭用ゲーム機、スマートフォン）にて配信される。",
        keywords: "デルタフォース、デルタフォース特殊部隊、Delta Force 、ブラックホークダウン、デルタフォースモバイルゲーム、デルタフォース新作、デルタフォースeスポーツ、FPS、デルタフォース公式サイト、eスポーツ、eスポーツ連携、SOL、マルチプラットフォーム",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "Japanese",
        lang: "ja",
        lang1: "アカウントのcdkey交換上限に達しました",
        lang2: "申し訳ございません、あなたはまだテスト資格を獲得していません。コミュニティの最新情報をご確認ください",
        lang3: "交換済み",
        lang4: "ログインしました",
        lang5: "受取成功！ゲーム内メールをご確認ください",
        lang6: "受取失敗。もう一度お試しください。",
        lang8: "今すぐログインして報酬を交換しましょう",
        lang9: "ログアウト",
        lang10: "引き換える",
        lang11: "ログイン",
        lang12: "入力したCDキーは無効です。もう一度お試しください。",
        lang178: "利用規約",
        lang179: "プライバシーポリシー",
        lang180: "Cookieポリシー",
        lang181: "License Information",
        networkError: "ネットワークエラー。しばらく時間をおいて再度お試しください",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        footLink3: "https://deltaforce.garena.com/en/"
    },
    tr: {
        "title": "Takas Merkezi",
        "description": "Delta Force, ücretsiz oynanabilen en gelişmiş birinci şahıs taktiksel nişancı oyunudur. PC, oyun konsolları ve mobil cihazlarda oynanabilir.",
        "keywords": "Delta Force, Delta Force, Delta Force Mobil, Delta Force Online, DF Mobil, Delta Force Ana Sayfa, FPS, e-spor, takım oyunu, strateji oyunu, SOL, profesyonel oyun ipuçları, taktik oyunu, karakter sınıflı, taktiksel atış",
        "shareUrl": "${HOST_NAME}/${LANG}/cdkgarena.html",
        "shareImg": "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        "notes": "Turkish",
        "lang": "tr",
        "lang1": "Üzgünüz, hesabın bu hediye paketinin daha fazla CDKey kullanımı için uygun değil.",
        "lang2": "Üzgünüz, henüz test için erişimin yok. Gelecek erişim hakları için topluluk güncellemelerini takip et.",
        "lang3": "Kullanıldı",
        "lang4": "Giriş Başarılı",
        "lang5": "Başarıyla alındı! Lütfen oyundaki posta kutunu kontrol et.",
        "lang6": "Alınamadı. Lütfen daha sonra tekrar dene",
        "lang8": "Oturum Aç ve Hemen Kullan",
        "lang9": "Oturumu Kapat",
        "lang10": "Kullan",
        "lang11": "Oturum Aç",
        "lang12": "Girilen CDKey geçerli değil. Lütfen tekrar deneyin.",
        "lang178": "Kullanım Koşulları",
        "lang179": "Gizlilik Politikası",
        "lang180": "Çerez Politikası",
        "lang181": "License Information",
        "networkError": "Ağ hatası. Lütfen daha sonra tekrar dene.",
        "lang_1": "Önceden kullanmışsın.",
        "event_reward": "Etkinlik Ödülü",
        "copyright": "Tebrikler! Bir etkinlik ödülü aldın. Ödülü ekte bulabilirsin. Etkinliğe katıldığın için teşekkürler, oyunun tadını çıkar!",
        "creator_reward": "İçerik Üreticisi Ödülleri",
        "creator_thanks_hint": "İçerik Üreticisi Etkinliğine katıldığın için teşekkür ederiz. Umarız Garena Delta Force® - Official'ta çok eğlenirsin!",
        "footLink1": "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        "footLink2": "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        "footLink3": "https://deltaforce.garena.com/tr/",
        "error_hint_400067": "CD anahtarı kullanım sınırına ulaşıldı.",
        "error_hint_400068": "Geçerli kullanıcı, CD anahtarı grubu kullanım sınırına ulaşmıştır.",
        "error_hint_400069": "CD anahtarı kullanımı henüz mevcut değil.",
        "error_hint_400070": "Bu CD anahtarı kullanım süresi sona erdi.",
        "error_hint_400072": "Kullanıcı, CD anahtarını zaten kullanmış.",
        "error_hint_400073": "CD anahtarı paketi yapılandırma hatası."
    },
    ms: {
        title: "Delta Force Pusat Penebusan",
        description: "Delta Force ialah permainan menembak taktikal pihak pertama yang percuma untuk main. Tersedia di PC, konsol dan peranti mudah alih.",
        keywords: "Delta Force, Pasukan Operasi Khas Delta Force, Delta Force, Black Hawk Down, Permainan Mudah Alih Delta Force, Permainan Baharu Delta Force, e-Sukan Delta Force, FPS, Web Rasmi Delta Force, e-Sukan, e-Sukan bekerjasama, SOL, berbilang platform",
        shareUrl: "${HOST_NAME}/${LANG}/cdkgarena.html",
        shareImg: "${HOST_NAME}/ossweb-img/main_share_icon.v2.png",
        notes: "Malay",
        lang: "ms",
        lang1: "Harap maaf, akaun anda tidak boleh menebus lagi CDKey untuk pek hadiah ini.",
        lang2: "Harap maaf, anda masih belum memperoleh akses kepada ujian. Ikuti kemas kini komuniti kami untuk pemberian yang akan datang.",
        lang3: "Dituntut",
        lang4: "Log Masuk Berjaya",
        lang5: "Berjaya dituntut! Sila semak mel dalam permainan anda.",
        lang6: "Gagal dituntut. Sila cuba lagi nanti.",
        lang8: "Log masuk dan Tebus Sekarang",
        lang9: "Log keluar",
        lang10: "Tebus",
        lang11: "Log Masuk",
        lang12: "CDKey yang dimasukkan tidak sah. Sila cuba lagi.",
        lang178: "Terma Perkhidmatan",
        lang179: "Perjanjian Privasi",
        lang180: "Perjanjian Kuki",
        lang181: "License Information",
        networkError: "Ralat rangkaian, sila cuba lagi sebentar lagi",
        footLink1: "https://contentgarena-a.akamaihd.net/legal/tos/tos_en.html",
        footLink2: "https://contentgarena-a.akamaihd.net/legal/pp/pp_en.html",
        footLink3: "https://deltaforce.garena.com/en/"
    },
};


try {
    window.GLanguage = GLanguage;
} catch (error) {
    console.log("===Window===");
}

try {
    exports.default = GLanguage;
} catch (error) {
    console.log("===node===");
}